"use client"

import type { Metadata } from "next";
import "./globals.css";
import React, {useEffect, useState} from "react";
import Link from "next/link";

// export const metadata: Metadata = {
//   title: "Web Tutorials",
//   description: "Generated by happykoo",
// };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  const [topics, setTopics] = useState([]);
  useEffect(() => {
    fetch('http://localhost:9999/topics')
      .then(resp => resp.json())
      .then(result => {
        setTopics(result);
      });
  }, []);

  return (
    <html>
      <body>
        <main>
          <h1><Link href="/">WEB</Link></h1>
          <ol>

            {topics.map((topic: any) => {
              return <li key={topic?.id}><Link href={`/read/${topic?.id}`}>{topic?.title}</Link></li>
            })}
          </ol>
          {children}
          <ul>
            <li><Link href={"/create"}>CREATE</Link></li>
            <li><Link href={"/update/1"}>UPDATE</Link></li>
            <li><button>delete</button></li>
          </ul>
        </main>
      </body>
    </html>
  );
}
