import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Control from "@/app/Control";

export const metadata: Metadata = {
  title: "Web Tutorials",
  description: "Generated by happykoo",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  // const resp = await fetch('http://127.0.0.1:9999/topics', { cache: 'no-store' });
  const resp = await fetch('http://127.0.0.1:9999/topics');
  const topics = await resp.json();

  return (
    <html>
      <body>
        <main>
          <h1><Link href="/">WEB</Link></h1>
          <ol>

            {topics.map((topic: any) => {
              return <li key={topic?.id}><Link href={`/read/${topic?.id}`}>{topic?.title}</Link></li>
            })}
          </ol>
          {children}
          <Control />
        </main>
      </body>
    </html>
  );
}
